### ISSUE TITLE
税率対象品目の登録・管理をおこなう

### ISSUE THREAD

**Issue by maho-ya** [maho-ya/ec#10]
税率対象品目の登録・管理をおこなう。軽減税率の対象品目と通常税率の管理に使用

# TODO
- [x] 税率対象品目のmodelの作成をおこなう。
  - [x] model用spec（TaxItem）の作成をおこなう。
  - [x] model（TaxItem）の作成をおこなう。
- [x] 税率対象品目の一覧表示機能の作成をおこなう。
- [x] 税率対象品目の登録機能の作成をおこなう。
- [x] 税率対象品目の更新機能の作成をおこなう。
- [x] 税率対象品目の削除機能の作成をおこなう。

**Comment by maho-ya** [comment]
# TODO - model（TaxItem）の作成をおこなう
- [ ] TaxItem
  - [ ] 追加・更新・削除
    - [ ] 追加
      - [ ] 税率対象品目が追加できること
      - [ ] 税率対象品目が複数追加できること
    - [ ] 更新
      - [ ] 税率対象品目が更新できること
    - [ ] 削除
      - [ ] 税率対象品目が削除できること
  - [ ] バリデーション
    - [ ] 税率対象品目名の確認をおこなう
      - [ ] 税率対象品目名が未入力であれば無効であること
      - [ ] 税率対象品目名が2文字以上でなければ無効であること
      - [ ] 税率対象品目名が40文字以内でなければ無効であること
    - [ ] 税率対象品目区分の確認をおこなう
      - [ ] 税率対象品目区分が未入力であれば無効であること
      - [ ] 税率対象品目区分が数値でなければ無効であること
