### ISSUE TITLE
カテゴリーの登録・管理をおこなう

### ISSUE THREAD

**Issue by maho-ya** [maho-ya/ec#11]
カテゴリーの登録・管理をおこなう。商品の検索やフロントエンドのカテゴリーメニューに関連づけられる

# TODO
- [x] カテゴリーのmodelの作成をおこなう。
  - [x] model用spec（Category）の作成をおこなう。
  - [x] model（Category）の作成をおこなう。
- [x] カテゴリーの一覧表示機能の作成をおこなう。
- [x] カテゴリーの登録機能の作成をおこなう。
- [x] カテゴリーの更新機能の作成をおこなう。
- [x] カテゴリーの削除機能の作成をおこなう。

**Comment by maho-ya** [comment]
# TODO - model（Category）の作成をおこなう
- [ ] Category
  - [ ] 追加・更新・削除
    - [ ] 追加
      - [ ] カテゴリーが追加できること
      - [ ] カテゴリーが複数追加できること
    - [ ] 更新
      - [ ] カテゴリーが更新できること
    - [ ] 削除
      - [ ] カテゴリーが削除できること
  - [ ] バリデーション
    - [ ] カテゴリー名の確認をおこなう
      - [ ] カテゴリー名が未入力であれば無効であること
      - [ ] カテゴリー名が2文字以上でなければ無効であること
      - [ ] カテゴリー名が40文字以内でなければ無効であること
    - [ ] 掲載開始日時の確認をおこなう
      - [ ] 掲載開始日時が日時でなければ無効であること
    - [ ] 掲載終了日時の確認をおこなう
      - [ ] 掲載終了日時が日時でなければ無効であること

**Comment by maho-ya** [comment]
カテゴリーの登録フォーム用のmodelを作成する。
日・時でコントロールを分けるため、別々に値を設定できるようにする。

TODO - model（CategoryForm）の作成をおこなう
- [ ] CategoryForm
  - [ ] 追加・更新・削除
    - [ ] 追加
      - [ ] カテゴリーが追加できること
      - [ ] カテゴリーが複数追加できること
    - [ ] 更新
      - [ ] カテゴリーが更新できること
    - [ ] 削除
      - [ ] カテゴリーが削除できること
  - [ ] バリデーション
    - [ ] 掲載開始日時の確認をおこなう
      - [ ] 掲載開始日・時がnilを許容すること
      - [ ] 掲載開始日・時がnilでも日・時でもなければ無効であること
      - [ ] 掲載開始日時が掲載終了日時より大きい場合無効であること
    - [ ] 掲載終了日時の確認をおこなう
      - [ ] 掲載終了日時がnilを許容すること
      - [ ] 掲載終了日時がnilでも日時でなければ無効であること

**Comment by maho-ya** [comment]
日・時で別の入力コントロールにしていたためCategoryFormにmodelを分けていたが統一。
