### ISSUE TITLE
商品の登録・管理をおこなう

### ISSUE THREAD

**Issue by maho-ya** [maho-ya/ec#12]
商品の登録・管理をおこなう。注文可能な商品を登録する

# TODO
- [ ] 商品のmodelの作成をおこなう。
  - [ ] model用spec（Item）の作成をおこなう。
  - [ ] model（Item）の作成をおこなう。
- [ ] 商品の一覧表示機能の作成をおこなう。
- [ ] 商品の登録機能の作成をおこなう。
- [ ] 商品の更新機能の作成をおこなう。
- [ ] 商品の削除機能の作成をおこなう。

**Comment by maho-ya** [comment]
# TODO - model（Item）の作成をおこなう
- [ ] Item
  - [ ] 追加・更新・削除
    - [ ] 追加
      - [ ] 商品が追加できること
      - [ ] 商品が複数追加できること
    - [ ] 更新
      - [ ] 商品が更新できること
    - [ ] 削除
      - [ ] 商品が削除できること
  - [ ] バリデーション
    - [ ] 商品名の確認をおこなう
      - [ ] 商品名が未入力であれば無効であること
      - [ ] 商品名が2文字以上でなければ無効であること
      - [ ] 商品名が40文字以内でなければ無効であること
    - [ ] カテゴリーの確認をおこなう
      - [ ] カテゴリーが未入力であれば無効であること
      - [ ] カテゴリーがnilを許容すること
      - [ ] カテゴリーマスタに存在しないカテゴリーならば無効であること
    - [ ] メーカー名の確認をおこなう
      - [ ] メーカー名がnilを許容すること
      - [ ] メーカー名がnilでなく2文字以上でなければ無効であること
      - [ ] メーカー名が40文字以内でなければ無効であること
    - [ ] 商品コードの確認をおこなう
      - [ ] 商品コードがnilを許容すること
      - [ ] 商品コードが32文字以内でなければ無効であること
      - [ ] すでに存在する商品コードならば無効であること
    - [ ] 税率対象品目の確認をおこなう
      - [ ] 税率対象品目が未入力であれば無効であること
      - [ ] 税率対象品目に存在しないカテゴリーならば無効であること
    - [ ] 販売価格の確認をおこなう
      - [ ] 販売価格が数値でなければ無効であること
      - [ ] 販売価格がnilを許容すること
      - [ ] 販売価格がnilでなく0 〜 99,999,999でなければ無効であること
    - [ ] 標準価格の確認をおこなう
      - [ ] 標準価格が数値でなければ無効であること
      - [ ] 標準価格がnilを許容すること
      - [ ] 標準価格がnilでなく0 〜 99,999,999でなければ無効であること
    - [ ] 在庫数の確認をおこなう
      - [ ] 在庫数が数値でなければ無効であること
      - [ ] 在庫数がnilを許容すること
      - [ ] 在庫数がnilでなく0 〜 99,999,999でなければ無効であること
    - [ ] 在庫数無制限の確認をおこなう
      - [ ] 在庫数無制限が真偽値でなければ無効であること
      - [ ] 在庫数無制限がnilを許容しないこと
    - [ ] 掲載開始日時の確認をおこなう
      - [ ] 掲載開始日時が日時でなければ無効であること
      - [ ] 掲載開始日時がnilを許容すること
      - [ ] 掲載開始日時が掲載終了日時より小さくなければ無効であること
    - [ ] 掲載終了日時の確認をおこなう
      - [ ] 掲載終了日時が日時でなければ無効であること
      - [ ] 掲載終了日時がnilを許容すること
      - [ ] 掲載終了日時が掲載開始日時より大きくなければ無効であること
    - [ ] 商品説明の確認をおこなう
      - [ ] 商品説明がnilを許容すること
      - [ ] 商品説明が1000文字以内でなければ無効であること
    - [ ] 検索文字列の確認をおこなう
      - [ ] 検索文字列がnilを許容すること
      - [ ] 検索文字列が40文字以内でなければ無効であること
    - [ ] JANコードの確認をおこなう
      - [ ] JANコードがnilを許容すること
      - [ ] JANコードが32文字以内でなければ無効であること
    - [ ] 商品状態の確認をおこなう
      - [ ] 商品状態がnilを許容しないこと
      - [ ] 商品状態が数値でなければ無効であること
      - [ ] 有効な商品状態でなければ無効であること
