### ISSUE TITLE
税区分の登録・管理をおこなう

### ISSUE THREAD

**Issue by maho-ya** [maho-ya/ec#19]
税区分の登録・管理をおこなう。消費税8%のような名称で税率を登録しておく

# TODO
- [x] 税区分のmodelの作成をおこなう。
  - [x] model用spec（TaxClass）の作成をおこなう。
  - [x] model（TaxClass）の作成をおこなう。
- [x] 税区分の一覧表示機能の作成をおこなう。
- [x] 税区分の登録機能の作成をおこなう。
- [x] 税区分の更新機能の作成をおこなう。
- [x] 税区分の削除機能の作成をおこなう。

**Comment by maho-ya** [comment]
# TODO - model（TaxClass）の作成をおこなう
- [ ] TaxClass
  - [ ] 追加・更新・削除
    - [ ] 追加
      - [ ] 税区分が追加できること
      - [ ] 税区分が複数追加できること
    - [ ] 更新
      - [ ] 税区分が更新できること
    - [ ] 削除
      - [ ] 税区分が削除できること
      - [ ] 税区分のIDが1であれば削除は無効であること
  - [ ] バリデーション
    - [ ] 税区分名の確認をおこなう
      - [ ] 税区分名が未入力であれば無効であること
      - [ ] 税区分名が2文字以上でなければ無効であること
      - [ ] 税区分名が40文字以内でなければ無効であること
    - [ ] 税率の確認をおこなう
      - [ ] 税率が未入力であれば無効であること
      - [ ] 税率が数値でなければ無効であること
