### ISSUE TITLE
税率管理の登録・管理をおこなう

### ISSUE THREAD

**Issue by maho-ya** [maho-ya/ec#27]
税率管理の登録・管理をおこなう。
税率適用開始日と標準税率・軽減税率を登録できるようにする。

# TODO
- [x] 税率管理のmodelの作成をおこなう。
  - [x] model用spec（TaxRate）の作成をおこなう。
  - [x] model（TaxRate）の作成をおこなう。
- [x] 税率管理の一覧表示機能の作成をおこなう。
- [x] 税率管理の登録機能の作成をおこなう。
- [x] 税率管理の更新機能の作成をおこなう。
- [x] 税率管理の削除機能の作成をおこなう。

**Comment by maho-ya** [comment]
# TODO spec
- [x] TaxRate
  - [x] 追加・更新・削除
    - [x] 追加
      - [x] 税率が追加できること
      - [x] 税率が複数追加できること
    - [x] 更新
      - [x] 税率が更新できること
    - [x] 削除
      - [x] 税率が削除できること
  - [x] バリデーション
    - [x] 名称の確認をおこなう
      - [x] 名称が未入力であれば無効であること
      - [x] 名称が2文字以上でなければ無効であること
      - [x] 名称が40文字以内でなければ無効であること
    - [x] 税率適用開始日の確認をおこなう
      - [x] 税率適用開始日がnilであれば無効であること
      - [x] 税率適用開始日が日付けでなければ無効であること
      - [x] すでに存在する税率適用開始日であれば無効であること
    - [x] 標準税率の確認をおこなう
      - [x] 標準税率が数値でなければ無効であること
      - [x] 標準税率がnilであれば無効であること
      - [x] 標準税率が最小値より小さければ無効であること
      - [x] 標準税率が最大値より大きければ無効であること
    - [x] 軽減税率の確認をおこなう
      - [x] 軽減税率が数値でなければ無効であること
      - [x] 軽減税率がnilを許容すること
      - [x] 軽減税率が最小値より小さければ無効であること
      - [x] 軽減税率が最大値より大きければ無効であること
