### ISSUE TITLE
スライドショーの登録・管理をおこなう

### ISSUE THREAD

**Issue by maho-ya** [maho-ya/ec#28]
スライドショーの登録・管理をおこなう。
画像を登録し、フロントのトップページに表示する。

# TODO
- [x] スライドショーのmodelの作成をおこなう。
  - [x] model用spec（Slideshow）の作成をおこなう。
  - [x] model（Slideshow）の作成をおこなう。
- [x] スライドショーの一覧表示機能の作成をおこなう。
- [x] スライドショーの登録機能の作成をおこなう。
- [x] スライドショーの更新機能の作成をおこなう。
- [x] スライドショーの削除機能の作成をおこなう。

**Comment by maho-ya** [comment]
# TODO model spec
- [x] Slideshow
  - [x] 追加・更新・削除
    - [x] 追加
      - [x] スライドショーが追加できること
      - [x] スライドショーが複数追加できること
    - [x] 更新
      - [x] スライドショーが更新できること
    - [x] 削除
      - [x] スライドショーが削除できること
  - [x] バリデーション
    - [x] スライドショー名の確認をおこなう
      - [x] スライドショー名が未入力であれば無効であること
      - [x] スライドショー名が最小文字以上でなければ無効であること
      - [x] スライドショー名が最大文字以内でなければ無効であること
    - [x] スライドショー詳細説明の確認をおこなう
      - [x] スライドショー詳細説明がnilを許容すること
      - [x] スライドショー詳細説明が最大文字以内でなければ無効であること
    - [x] URLの確認をおこなう
      - [x] URLがnilを許容すること
      - [x] URLが最大文字以内でなければ無効であること
    - [x] スライドショー画像の確認をおこなう
      - [x] スライドショー画像が登録できること
      - [x] スライドショー画像が削除できること
